action: train  # one of [train, train+valid, train+test, valid, test]
data:
  type: beta
  data_folder: data/FB15k-237-betae
  cpu: 10
train:
  negative_sample_size: 128  # for each positive sample
  batch_size: 512
  learning_rate: 0.0001
  steps: 100000
  log_every_steps: 100
  warm_up_steps: None
  meta_queries: 
    - 1p
    - 2p
    - 3p
    - 1i
    - 2i
evaluate:  # only used when valid/test in action
  batch_size: 1
  evaluate_every_steps: 30000
  log_every_steps: 100
  print: true
  tasks: 1p.2p.3p.1i.2i
logging:
  checkpoint_every: 50000
  logging_path: default
estimator:
  embedding: beta # one of [Transe, box, beta, dm]
  beta:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
  box:
    entity_dim: 400
    relation_dim: 400
    offset_activation: None
    center_reg: 0.02
  dm:
    entity_dim: 2
    relation_dim: 2
    hidden_dim: 1600
    num_layers: 2
