action: ['test']  # one of [train, train+valid, train+test, valid, test]
seed: 0
cuda: 0
data:
  type: benchmark
  data_folder: data/benchmark/FB15k-237
  cpu: 10
train:
  negative_sample_size: 128  # for each positive sample
  batch_size: 512
  learning_rate: 0.0001
  steps: 450000
  log_every_steps: 100
  warm_up_steps: 225000
  evaluate_every_steps: 15000
  save_every_steps: 10000
  checkpoint_every: 10000
  meta_queries:
evaluate:  # only used when valid/test in action
  batch_size: 1000
  print: true
  interested_normal_forms:
    - 'original'
    - 'DeMorgan'
    - 'DeMorgan+MultiI'
    - 'DNF'
    - 'diff'
    - 'DNF+diff'
    - 'DNF+MultiIU'
    - 'DNF+MultiIUd'
    - 'DNF+MUltiIUD'
  formula_id_file: 'data/test_generated_formula_anchor_node=3.csv'
estimator:
  embedding: logic # one of [Transe, box, beta, dm, logic]
  beta:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    evaluate_union: DM # one of [DM, DNF]
    gamma: 60
  box:
    entity_dim: 400
    relation_dim: 400
    offset_activation: None
    center_reg: 0.02
    gamma: 60
  dm:
    entity_dim: 2
    relation_dim: 2
    hidden_dim: 1600
    num_layers: 2
  logic:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    gamma: 0.375
    t_norm: luk
    bounded: 0
    use_att: 1
    use_gtrans: 0

