action: ['train','valid','test']  # one of [train, train+valid, train+test, valid, test]
seed: 0
cuda: 7
data:
  type: beta   # one of ['beta', 'sampled']
  data_folder: data/FB15k-237-foq
  cpu: 10
train:
  negative_sample_size: 128  # for each positive sample
  batch_size: 512
  learning_rate: 0.0001
  steps: 900000
  log_every_steps: 200
  warm_up_steps: 450000
  evaluate_every_steps: 30000
  save_every_steps: 20000
  checkpoint_every: 20000
  meta_queries:
     - 1p
     - 2i
     - 3i
evaluate:  # only used when valid/test in action
  batch_size: 1000
  print: true
  meta_queries:
     - 1p
     - 2i
     - 3i
estimator:
  embedding: logic # one of [Transe, box, beta, dm, logic]
  beta:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    evaluate_union: DM # one of [DM, DNF]
    gamma: 60
  box:
    entity_dim: 400
    relation_dim: 400
    offset_activation: None
    center_reg: 0.02
    gamma: 60
  dm:
    entity_dim: 2
    relation_dim: 2
    hidden_dim: 1600
    num_layers: 2
  logic:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    gamma: 0.375
    t_norm: luk
    bounded: 0
    use_att: 1
    use_gtrans: 0

